export const UIText = {
  homeTitle: "My FlashCards",
  homeSubTitle: "Chinese",
  startButton: "Start Review",
  cardClickSeeAnswer: "Click to see the",
  cardClickSeeAnswerHighlight: "answer",
  cardConfirmGetAnswer: "Did you get the answer?",
  rateButtonYes: "YES",
  rateButtonNotSure: "Not Sure",
  rateButtonNo: "NO",
  returnToHome: "Return to Home",
  congrats: "Congratulations!",
  studyFinish: "You finished all the words!",
  anotherRound: "Another round",
};
