export const vocabulary = [
  { id: 1, EN: "Hello", ZH: "你好", pin: "nǐ hǎo" },
  { id: 2, EN: "See you", ZH: "再见", pin: "zài jiàn" },
  { id: 3, EN: "Cat", ZH: "猫", pin: "māo" },
  { id: 4, EN: "Dog", ZH: "狗", pin: "gǒu" },
  { id: 5, EN: "School", ZH: "学校", pin: "xué xiào" },
  { id: 6, EN: "Teacher", ZH: "老师", pin: "lǎo shī" },
  { id: 7, EN: "Student", ZH: "学生", pin: "xué shēng" },
  { id: 8, EN: "Homework", ZH: "作业", pin: "zuò yè" },
  { id: 9, EN: "Classroom", ZH: "教室", pin: "jiào shì" },
  { id: 10, EN: "Computer", ZH: "电脑", pin: "diàn nǎo" },
  { id: 11, EN: "Coding", ZH: "编程", pin: "biān chéng" },
  { id: 12, EN: "Hungry", ZH: "饿", pin: "è" },
  { id: 13, EN: "Sugar", ZH: "糖", pin: "táng" },
  { id: 14, EN: "Caramel", ZH: "焦糖", pin: "jiāo táng" },
  { id: 15, EN: "Milk", ZH: "牛奶", pin: "niú nǎi" },
  { id: 16, EN: "Lobster", ZH: "龙虾", pin: "lóng xiā" },
  { id: 17, EN: "Apple", ZH: "苹果", pin: "píng guǒ" },
  { id: 18, EN: "Avocado", ZH: "牛油果", pin: "niú yóu guǒ" },
  { id: 19, EN: "Banana", ZH: "香蕉", pin: "xiāng jiāo" },
  { id: 20, EN: "Coconut", ZH: "椰子", pin: "yē zi" },
];
