export const vocabulary = [
  { EN: "Hello", ZH: "你好", pin: "nǐ hǎo" },
  { EN: "See you", ZH: "再见", pin: "zài jiàn" },
  { EN: "Dog", ZH: "狗", pin: "gǒu" },
  { EN: "Cat", ZH: "猫", pin: "māo" },
  { EN: "School", ZH: "学校", pin: "xué xiào" },
  { EN: "Teacher", ZH: "老师", pin: "lǎo shī" },
  { EN: "Student", ZH: "学生", pin: "xué shēng" },
  { EN: "Homework", ZH: "作业", pin: "zuò yè" },
  { EN: "Classroom", ZH: "教室", pin: "jiào shì" },
  { EN: "Computer", ZH: "电脑", pin: "diàn nǎo" },
  { EN: "Coding", ZH: "编程", pin: "biān chéng" },
  { EN: "Hungry", ZH: "饿", pin: "è" },
  { EN: "Sugar", ZH: "糖", pin: "táng" },
  { EN: "Caramel", ZH: "焦糖", pin: "jiāo táng" },
  { EN: "Milk", ZH: "牛奶", pin: "niú nǎi" },
  { EN: "Lobster", ZH: "龙虾", pin: "lóng xiā" },
  { EN: "Apple", ZH: "苹果", pin: "píng guǒ" },
  { EN: "Avocado", ZH: "牛油果", pin: "niú yóu guǒ" },
  { EN: "Banana", ZH: "香蕉", pin: "xiāng jiāo" },
  { EN: "Coconut", ZH: "椰子", pin: "yē zi" },
];
